const path = require("path");
const puppeteer = require("puppeteer");

const parseJsonContent = (rawContent) => {
  const cleaned = rawContent.replace(/```json|```/g, "").trim();
  const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
  const jsonString = jsonMatch ? jsonMatch[0] : cleaned;
  return JSON.parse(jsonString);
};

const ACCENTS = ["#14b8a6", "#8b5cf6", "#f59e0b", "#3b82f6", "#f87171", "#10b981"];
const color = (i) => ACCENTS[i % ACCENTS.length];

const BASE_STYLE = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', Calibri, Arial, sans-serif; background: linear-gradient(160deg, #1B2A4A 0%, #24365e 100%); }
  .footer { margin-top: 30px; text-align: center; font-size: 12px; color: rgba(255,255,255,0.6); letter-spacing: 1px; }
`;

const wrap = (bodyHtml, extraStyle = "", width = 1000) => `
  <html><head><style>${BASE_STYLE}${extraStyle} body { width: ${width}px; padding: 55px 55px; }</style></head>
  <body>${bodyHtml}<div class="footer">GENERATED BY MENTOSAI</div></body></html>`;

// 1. Hero — ek dominant stat/finding
const buildHero = ({ headline, sections }) => {
  const main = sections[0] || {};
  const rest = sections.slice(1);
  const restHtml = rest
    .map((s, i) => `
      <div class="row">
        <div class="row-dot" style="background:${color(i + 1)}"></div>
        <div><b>${s.label || ""}:</b> ${s.description || s.stat_or_point || ""}</div>
      </div>`)
    .join("");

  return wrap(`
    <div class="headline">${headline || ""}</div>
    <div class="hero-card">
      <div class="hero-label" style="color:${color(0)}">${main.label || ""}</div>
      <div class="hero-stat">${main.stat_or_point || ""}</div>
      <div class="hero-desc">${main.description || ""}</div>
    </div>
    ${rest.length ? `<div class="secondary">${restHtml}</div>` : ""}
  `, `
    .headline { font-size: 34px; font-weight: 800; color: #fff; margin-bottom: 35px; line-height: 1.25; }
    .hero-card { background: #fff; border-radius: 20px; padding: 40px; text-align: center; margin-bottom: 25px; }
    .hero-label { font-size: 14px; font-weight: 700; text-transform: uppercase; letter-spacing: 1.5px; margin-bottom: 10px; }
    .hero-stat { font-size: 52px; font-weight: 900; color: #1B2A4A; margin-bottom: 14px; line-height: 1.15; }
    .hero-desc { font-size: 16px; color: #475569; max-width: 700px; margin: 0 auto; }
    .secondary { background: rgba(255,255,255,0.06); border-radius: 14px; padding: 20px 24px; }
    .row { display: flex; align-items: center; gap: 12px; color: #fff; font-size: 14px; padding: 8px 0; }
    .row-dot { width: 10px; height: 10px; border-radius: 50%; flex-shrink: 0; }
  `, 780);
};

// 2. Highlight Strip — 2-3 chhote punchy stats
const buildStrip = ({ headline, sections }) => {
  const chips = sections
    .map((s, i) => `
      <div class="chip" style="border-top-color:${color(i)}">
        <div class="chip-stat" style="color:${color(i)}">${s.stat_or_point || ""}</div>
        <div class="chip-label">${s.label || ""}</div>
        <div class="chip-desc">${s.description || ""}</div>
      </div>`)
    .join("");

  return wrap(`
    <div class="headline">${headline || ""}</div>
    <div class="strip">${chips}</div>
  `, `
    .headline { font-size: 32px; font-weight: 800; color: #fff; margin-bottom: 35px; text-align: center; }
    .strip { display: flex; gap: 20px; justify-content: center; flex-wrap: wrap; }
    .chip { background: #fff; border-top: 6px solid; border-radius: 14px; padding: 26px 22px; width: 260px; text-align: center; box-shadow: 0 8px 20px rgba(0,0,0,0.15); }
    .chip-stat { font-size: 34px; font-weight: 900; margin-bottom: 8px; }
    .chip-label { font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: #64748b; margin-bottom: 8px; }
    .chip-desc { font-size: 13px; color: #475569; line-height: 1.4; }
  `, 900);
};

// 3. Grid — 4-6 balanced points (default)
const buildGrid = ({ headline, sections }) => {
  const cards = sections
    .map((s, i) => `
      <div class="card" style="border-top: 5px solid ${color(i)}">
        <div class="card-badge" style="background:${color(i)}">${String(i + 1).padStart(2, "0")}</div>
        <div class="card-label">${s.label || ""}</div>
        <div class="card-stat">${s.stat_or_point || ""}</div>
        <div class="card-desc">${s.description || ""}</div>
      </div>`)
    .join("");

  return wrap(`
    <div class="headline">${headline || ""}</div>
    <div class="grid">${cards}</div>
  `, `
    .headline { font-size: 38px; font-weight: 800; color: #fff; margin-bottom: 45px; line-height: 1.25; max-width: 850px; }
    .grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 24px; }
    .card { background: #fff; border-radius: 16px; padding: 26px 28px; box-shadow: 0 10px 30px rgba(0,0,0,0.15); position: relative; }
    .card-badge { position: absolute; top: -16px; right: 20px; width: 34px; height: 34px; border-radius: 50%; color: #fff; font-size: 13px; font-weight: 800; display: flex; align-items: center; justify-content: center; }
    .card-label { font-size: 13px; font-weight: 700; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; }
    .card-stat { font-size: 24px; font-weight: 800; color: #1B2A4A; margin-bottom: 10px; line-height: 1.3; }
    .card-desc { font-size: 13.5px; color: #475569; line-height: 1.5; }
  `, 1000);
};

// 4. Timeline — sequential steps
const buildTimeline = ({ headline, sections }) => {
  const items = sections
    .map((s, i) => {
      const isLast = i === sections.length - 1;
      return `
      <div class="step">
        <div class="step-marker">
          <div class="step-circle" style="background:${color(i)}">${i + 1}</div>
          ${isLast ? "" : `<div class="step-line"></div>`}
        </div>
        <div class="step-content">
          <div class="step-label" style="color:${color(i)}">${s.label || ""}</div>
          <div class="step-stat">${s.stat_or_point || ""}</div>
          <div class="step-desc">${s.description || ""}</div>
        </div>
      </div>`;
    })
    .join("");

  return wrap(`
    <div class="headline">${headline || ""}</div>
    ${items}
  `, `
    .headline { font-size: 34px; font-weight: 800; color: #fff; margin-bottom: 40px; line-height: 1.25; }
    .step { display: flex; gap: 24px; }
    .step-marker { display: flex; flex-direction: column; align-items: center; }
    .step-circle { width: 44px; height: 44px; border-radius: 50%; color: #fff; font-weight: 800; font-size: 18px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    .step-line { width: 3px; flex: 1; background: rgba(255,255,255,0.25); margin: 4px 0; min-height: 30px; }
    .step-content { background: #fff; border-radius: 14px; padding: 20px 24px; margin-bottom: 22px; flex: 1; box-shadow: 0 8px 20px rgba(0,0,0,0.15); }
    .step-label { font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px; }
    .step-stat { font-size: 21px; font-weight: 800; color: #1B2A4A; margin-bottom: 8px; }
    .step-desc { font-size: 13.5px; color: #475569; line-height: 1.5; }
  `, 900);
};

// 5. Ranked List — 6+ items, compact rows
const buildList = ({ headline, sections }) => {
  const rows = sections
    .map((s, i) => `
      <div class="list-row">
        <div class="list-badge" style="background:${color(i)}">${i + 1}</div>
        <div class="list-text">
          <span class="list-label">${s.label || ""}</span>
          <span class="list-stat" style="color:${color(i)}">${s.stat_or_point || ""}</span>
          <div class="list-desc">${s.description || ""}</div>
        </div>
      </div>`)
    .join("");

  return wrap(`
    <div class="headline">${headline || ""}</div>
    <div class="list">${rows}</div>
  `, `
    .headline { font-size: 32px; font-weight: 800; color: #fff; margin-bottom: 30px; }
    .list { background: #fff; border-radius: 16px; overflow: hidden; }
    .list-row { display: flex; gap: 16px; padding: 16px 22px; border-bottom: 1px solid #eef0f3; align-items: flex-start; }
    .list-row:last-child { border-bottom: none; }
    .list-badge { width: 30px; height: 30px; border-radius: 50%; color: #fff; font-weight: 800; font-size: 13px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; margin-top: 2px; }
    .list-label { font-weight: 700; color: #1B2A4A; font-size: 14.5px; }
    .list-stat { font-weight: 700; font-size: 14px; margin-left: 8px; }
    .list-desc { font-size: 13px; color: #64748b; margin-top: 3px; }
  `, 900);
};

const chooseLayout = ({ sections = [], layoutSuggestion = "" }) => {
  const n = sections.length;
  const s = layoutSuggestion.toLowerCase();

  if (n <= 1) return buildHero;
  if (/(flow|step|sequence|process|timeline|order|stage)/.test(s)) return buildTimeline;
  if (n > 6 || /(rank|top \d|priority|checklist)/.test(s)) return buildList;
  if (n <= 3) return buildStrip;
  return buildGrid;
};

const toInfographicImage = async (rawContent) => {
  const data = parseJsonContent(rawContent);
  const builder = chooseLayout(data);
  const html = builder(data);

  const fileName = `infographic-${Date.now()}.png`;
  const filePath = path.join(__dirname, "../../../outputs", fileName);

  const browser = await puppeteer.launch({ headless: "new" });
  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 1000, height: 800 });
    await page.setContent(html, { waitUntil: "networkidle0" });
    await page.screenshot({ path: filePath, fullPage: true });
  } finally {
    await browser.close();
  }

  return fileName;
};

module.exports = { toInfographicImage };


// const path = require("path");
// const fs = require("fs");
// const { generateImage } = require("../../services/llm.service");

// const parseJsonContent = (rawContent) => {
//   const cleaned = rawContent.replace(/```json|```/g, "").trim();
//   const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
//   const jsonString = jsonMatch ? jsonMatch[0] : cleaned;
//   return JSON.parse(jsonString);
// };

// const buildImagePrompt = ({ headline, sections = [], layoutSuggestion }) => {
//   const sectionText = sections
//     .map((s, i) => `${i + 1}. ${s.label}: "${s.stat_or_point}" — ${s.description}`)
//     .join("\n");

//   return `Design a clean, modern, professional infographic image.

// Headline: "${headline}"

// Sections (render this exact text accurately, do not change wording or numbers):
// ${sectionText}

// Layout guidance: ${layoutSuggestion || "a well-organized, visually balanced layout appropriate to this content"}

// Style: dark navy background, white content cards, teal/purple/amber accent colors, bold sans-serif typography, generous spacing, no clutter. Include a small "Generated by MentosAI" label at the bottom. High resolution, suitable for a business presentation.`;
// };

// const toInfographicImage = async (rawContent) => {
//   const data = parseJsonContent(rawContent);
//   const prompt = buildImagePrompt(data);

//   const imageBuffer = await generateImage(prompt);

//   const fileName = `infographic-${Date.now()}.png`;
//   const filePath = path.join(__dirname, "../../../outputs", fileName);
//   fs.writeFileSync(filePath, imageBuffer);

//   return fileName;
// };

// module.exports = { toInfographicImage };